---
# Example password is "Password", you must change this

alternative_user: "user"
alternative_user_password: "$6$6nnSiMHYKIN6xDLs$tDyRO7SyM5LUFO4xlSiQ4NZpgPxyckYg4dGBTc22rhCEFux6LHO7BW857EQbOMb58eUU3f4.lE8iO3BE.JyPp/"

# Paths to sudoers.d and sshd_config

pi_sudoersd_path: "/etc/sudoers.d/010_pi-nopasswd"
sshd_config_path: "/etc/ssh/sshd_config"

