---

      - name: Include variables file
        include_vars:
          file: "vars/main.yaml"

      - name: Update apt packages list
        apt:
          upgrade: no
          update_cache: yes
          cache_valid_time: 86400

      - name: Install required packages
        apt:
          name: "{{ item }}"
        with_items:
          - ufw
          - fail2ban

      - name: Create alternative user
        user:
          name: "{{ alternative_user }}"
          group: sudo
          uid: 501
          password: "{{ alternative_user_password }}"
          state: present
          update_password: always
          shell: /bin/bash

      - name: Set users that are allowed to use SSH
        lineinfile:
          path: "{{ sshd_config_path }}"
          insertafter: "EOF"
          line: "AllowUsers {{ alternative_user }}"

      - name: Set users that are not allowed to use SSH
        lineinfile:
          path: "{{ sshd_config_path }}"
          insertafter: "EOF"
          line: "DenyUsers pi root"

      - name: Copy authorized_keys file to server
        copy:
          src: files/authorized_keys
          dest: "/home/{{ alternative_user }}/.ssh/"
          owner: "{{ alternative_user }}"
          group: root
          mode: 0644

      - name: Disable ChallengeResponseAuthentication
        lineinfile:
          path: "{{ sshd_config_path }}"
          regexp: "^ChallengeResponseAuthentication"
          line: "ChallengeResponseAuthentication no"

      - name: Disable PasswordAuthentication
        lineinfile:
          path: "{{ sshd_config_path }}"
          regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"

      - name: Disable UsePAM
        lineinfile:
          path: "{{ sshd_config_path }}"
          regexp: "^UsePAM"
          line: "UsePAM no"

      - name: Start and enable UFW
        ufw:
          state: enabled

      - name: Establish default incoming firewall rule
        ufw:
          policy: deny
          direction: incoming

      - name: Establish default outgoing firewall rule
        ufw:
          policy: allow
          direction: outgoing

      - name: Establish ssh firewall rule
        ufw:
          rule: limit
          port: ssh
          proto: tcp

      - name: Copy jail.local file to server
        copy:
          src: files/jail.local
          dest: "/etc/fail2ban/"
          owner: root
          group: root
          mode: 0644

