---

      - name: Include variables file
        include_vars:
          file: "vars/main.yaml"

      - name: Update apt packages list
        apt:
          upgrade: no
          update_cache: yes
          cache_valid_time: 86400

      - name: Install required packages
        apt:
          name: "{{ item }}"
        with_items:
          - ufw
          - fail2ban

      - name: Change the password of the user pi
        user:
          name: pi
          password: "{{ pi_custom_password }}"
          state: present
          update_password: always

      - name: Create alternative user
        user:
          name: "{{ alternative_user }}"
          group: sudo
          uid: 501
          password: "{{ alternative_user_password }}"
          state: present
          update_password: always
          shell: /bin/bash

      - name: Set users that are allowed to use SSH
        lineinfile:
          path: "{{ sshd_config_path }}"
          insertafter: "EOF"
          line: "AllowUsers {{ alternative_user }}"

      - name: Set users that are not allowed to use SSH
        lineinfile:
          path: "{{ sshd_config_path }}"
          insertafter: "EOF"
          line: "DenyUsers pi root"

      - name: Copy authorized_keys file to Raspberry Pi
        copy:
          src: files/authorized_keys
          dest: "/home/{{ alternative_user }}/.ssh/"
          owner: "{{ alternative_user }}"
          group: root
          mode: 0644

      - name: Disable ChallengeResponseAuthentication
        lineinfile:
          path: "{{ sshd_config_path }}"
          regexp: "^ChallengeResponseAuthentication"
          line: "ChallengeResponseAuthentication no"

      - name: Disable PasswordAuthentication
        lineinfile:
          path: "{{ sshd_config_path }}"
          regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"

      - name: Disable UsePAM
        lineinfile:
          path: "{{ sshd_config_path }}"
          regexp: "^UsePAM"
          line: "UsePAM no"

### UFW muss einen reboot triggern

      - name: Start and enable UFW
        ufw:
          state: enabled

      - name: Establish default incoming firewall rule
        ufw:
          policy: deny
          direction: incoming

      - name: Establish default outgoing firewall rule
        ufw:
          policy: allow
          direction: outgoing

      - name: Establish ssh firewall rule
        ufw:
          rule: limit
          port: ssh
          proto: tcp

      - name: Copy jail.local file to Raspberry Pi
        copy:
          src: files/jail.local
          dest: "/etc/fail2ban/"
          owner: root
          group: root
          mode: 0644

      - name: Make sudo require a password for the pi user
        lineinfile:
          path: "{{ pi_sudoersd_path }}"
          regexp: "^pi"
          line: "pi ALL=(ALL) PASSWD: ALL"

      - name: Configure options in /boot/config.txt.
        lineinfile:
          dest: /boot/config.txt
          regexp: "{{ item.regexp }}"
          line: "{{ item.line }}"
          insertafter: EOF
          state: present
          with_items: "{{ raspberry_pi_boot_config_options }}"
